# **Part 3 Feature Engg**

In [26]:
import numpy as np
import pandas as pd

In [28]:
df1 = pd.read_parquet('clicks_cleaned.parquet')
df2 = pd.read_parquet('installs.parquet')
df3 = pd.read_parquet('revenue.parquet')

In [29]:
df1.info()
df1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4997003 entries, 0 to 4997002
Data columns (total 9 columns):
 #   Column        Dtype
---  ------        -----
 0   click_id      int64
 1   campaign_id   int64
 2   publisher_id  int64
 3   user_id       int64
 4   device_type   object
 5   country       object
 6   cost          float64
 7   timestamp     datetime64[ns]
 8   ip_address    object
dtypes: datetime64[ns](1), float64(1), int64(4), object(3)
memory usage: 343.1+ MB

,click_id,campaign_id,publisher_id,user_id,device_type,country,cost,timestamp,ip_address
0,1,150,83,406708,android,usa,0.300000,2024-03-01 18:22:42,48.47.128.218
1,2,136,57,902009,ios,germany,0.513611,2024-09-16 11:43:17,21.64.38.117
2,3,26,33,595169,android,india,0.200000,2024-09-23 09:00:55,207.241.26.48
3,4,105,5,675095,ios,unknown,0.480000,2024-11-17 04:07:10,168.210.213.174
4,5,23,94,112516,android,india,0.290000,2024-08-18 04:57:58,149.240.238.164

In [30]:
df1['timestamp'] = pd.to_datetime(df1['timestamp'], errors='coerce')

In [31]:
df1['timestamp'].isna().sum()

np.int64(0)

In [32]:
df1 = df1.dropna(subset=['timestamp'])

In [33]:
df1['click_date'] = df1['timestamp'].dt.date
df1['click_hour'] = df1['timestamp'].dt.hour
df1['click_minute'] = df1['timestamp'].dt.minute
df1['day_of_week'] = df1['timestamp'].dt.day_name()
df1['week_number'] = df1['timestamp'].dt.isocalendar().week
df1['month'] = df1['timestamp'].dt.month

In [36]:
df1['hour_bucket'] = df1['timestamp'].dt.floor('H')
df1['minute_bucket'] = df1['timestamp'].dt.floor('T')

/tmp/ipykernel_1560/2792400797.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df1['hour_bucket'] = df1['timestamp'].dt.floor('H')
/tmp/ipykernel_1560/2792400797.py:2: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df1['minute_bucket'] = df1['timestamp'].dt.floor('T')

In [39]:
df1['click_date'] = pd.to_datetime(df1['click_date'])

In [40]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4997003 entries, 0 to 4997002
Data columns (total 17 columns):
 #   Column         Dtype
---  ------         -----
 0   click_id       int64
 1   campaign_id    int64
 2   publisher_id   int64
 3   user_id        int64
 4   device_type    object
 5   country        object
 6   cost           float64
 7   timestamp      datetime64[ns]
 8   ip_address     object
 9   click_date     datetime64[ns]
 10  click_hour     int32
 11  click_minute   int32
 12  day_of_week    object
 13  week_number    UInt32
 14  month          int32
 15  hour_bucket    datetime64[ns]
 16  minute_bucket  datetime64[ns]
dtypes: UInt32(1), datetime64[ns](4), float64(1), int32(3), int64(4), object(4)
memory usage: 576.6+ MB

In [38]:
df1.head()

,click_id,campaign_id,publisher_id,user_id,device_type,country,cost,timestamp,ip_address,click_date,click_hour,click_minute,day_of_week,week_number,month,hour_bucket,minute_bucket
0,1,150,83,406708,android,usa,0.300000,2024-03-01 18:22:42,48.47.128.218,2024-03-01,18,22,Friday,9,3,2024-03-01 18:00:00,2024-03-01 18:22:00
1,2,136,57,902009,ios,germany,0.513611,2024-09-16 11:43:17,21.64.38.117,2024-09-16,11,43,Monday,38,9,2024-09-16 11:00:00,2024-09-16 11:43:00
2,3,26,33,595169,android,india,0.200000,2024-09-23 09:00:55,207.241.26.48,2024-09-23,9,0,Monday,39,9,2024-09-23 09:00:00,2024-09-23 09:00:00
3,4,105,5,675095,ios,unknown,0.480000,2024-11-17 04:07:10,168.210.213.174,2024-11-17,4,7,Sunday,46,11,2024-11-17 04:00:00,2024-11-17 04:07:00
4,5,23,94,112516,android,india,0.290000,2024-08-18 04:57:58,149.240.238.164,2024-08-18,4,57,Sunday,33,8,2024-08-18 04:00:00,2024-08-18 04:57:00

In [ ]:
###############################################

In [56]:
df1.to_csv("clicks_f1.csv", index=False)

In [ ]:
###############################################

In [42]:
df2['install_timestamp'] = pd.to_datetime(df2['install_timestamp'], errors='coerce')

In [43]:
df2['install_timestamp'].isna().sum()

np.int64(0)

In [44]:
df2 = df2.dropna(subset=['install_timestamp'])

In [45]:
df2['install_date'] = df2['install_timestamp'].dt.normalize()
df2['install_hour'] = df2['install_timestamp'].dt.hour
df2['install_week'] = df2['install_timestamp'].dt.isocalendar().week

In [46]:
df2.duplicated().sum()

np.int64(0)

In [66]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   install_id         250000 non-null  int64
 1   click_id           250000 non-null  int64
 2   install_timestamp  250000 non-null  datetime64[ns]
 3   install_date       250000 non-null  datetime64[ns]
 4   install_hour       250000 non-null  int32
 5   install_week       250000 non-null  UInt32
dtypes: UInt32(1), datetime64[ns](2), int32(1), int64(2)
memory usage: 9.8 MB

In [57]:
###################################################
df2.to_csv("installs_f1.csv", index=False)

In [ ]:
###################################################

In [48]:
df3['event_timestamp'] = pd.to_datetime(df3['event_timestamp'], errors='coerce')

In [49]:
df3['event_timestamp'].isna().sum()

np.int64(0)

In [50]:
df3 = df3.dropna(subset=['event_timestamp'])

In [54]:
df3['revenue_date'] = df3['event_timestamp'].dt.normalize()
df3['revenue_week'] = df3['event_timestamp'].dt.isocalendar().week
df3['revenue_month'] = df3['event_timestamp'].dt.month

In [55]:
df3.head()

,user_id,revenue,event_timestamp,event_type,revenue_date,revenue_week,revenue_month
0,374,2.38,2024-09-20 06:31:33,purchase,2024-09-20,38,9
1,947335,35.02,2024-02-13 07:51:47,purchase,2024-02-13,7,2
2,904215,21.05,2024-11-19 23:11:00,subscription,2024-11-19,47,11
3,362117,18.09,2024-07-31 11:10:49,purchase,2024-07-31,31,7
4,246216,9.66,2024-07-16 22:07:00,subscription,2024-07-16,29,7

In [58]:
#############################################################
df3.to_csv("revenue_f1.csv", index=False)

In [ ]:
#######
## JOINING ##

In [61]:
df4 = pd.read_csv('clicks_f1.csv')
df5 = pd.read_csv('installs_f1.csv')
df6 = pd.read_csv('revenue_f1.csv')

In [63]:
df = df4.merge(df5, on='click_id', how='left')

In [71]:
df['install_flag'] = df['install_timestamp'].notna().astype(int)

In [72]:
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
df['install_timestamp'] = pd.to_datetime(df['install_timestamp'], errors='coerce')

In [73]:
df[['timestamp','install_timestamp']].dtypes

timestamp            datetime64[ns]
install_timestamp    datetime64[ns]
dtype: object

In [74]:
df['time_to_install'] = (df['install_timestamp'] - df['timestamp']).dt.total_seconds()

In [75]:
df6_agg = df6.groupby('user_id')['revenue'].sum().reset_index()

In [76]:
df = df.merge(df6_agg, on='user_id', how='left')

In [77]:
df['revenue'] = df['revenue'].fillna(0)

In [78]:
print(df.shape)
df.head()

(4997003, 25)

,click_id,campaign_id,publisher_id,user_id,device_type,country,cost,timestamp,ip_address,click_date,...,hour_bucket,minute_bucket,install_id,install_timestamp,install_date,install_hour,install_week,install_flag,time_to_install,revenue
0,1,150,83,406708,android,usa,0.300000,2024-03-01 18:22:42,48.47.128.218,2024-03-01,...,2024-03-01 18:00:00,2024-03-01 18:22:00,NaN,NaT,NaN,NaN,NaN,0,NaN,0.0
1,2,136,57,902009,ios,germany,0.513611,2024-09-16 11:43:17,21.64.38.117,2024-09-16,...,2024-09-16 11:00:00,2024-09-16 11:43:00,NaN,NaT,NaN,NaN,NaN,0,NaN,0.0
2,3,26,33,595169,android,india,0.200000,2024-09-23 09:00:55,207.241.26.48,2024-09-23,...,2024-09-23 09:00:00,2024-09-23 09:00:00,NaN,NaT,NaN,NaN,NaN,0,NaN,0.0
3,4,105,5,675095,ios,unknown,0.480000,2024-11-17 04:07:10,168.210.213.174,2024-11-17,...,2024-11-17 04:00:00,2024-11-17 04:07:00,NaN,NaT,NaN,NaN,NaN,0,NaN,0.0
4,5,23,94,112516,android,india,0.290000,2024-08-18 04:57:58,149.240.238.164,2024-08-18,...,2024-08-18 04:00:00,2024-08-18 04:57:00,NaN,NaT,NaN,NaN,NaN,0,NaN,0.0

In [80]:
df.to_csv("final_dataset.csv", index=False)

In [81]:
df.to_parquet("final_dataset.parquet", index=False)